/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mundoludo.modern3d;

import com.mundoludo.modern3d.tut01.HelloTriangle;
import com.mundoludo.modern3d.tut02.FragPosition;
import com.mundoludo.modern3d.tut02.VertexColors;
import com.mundoludo.modern3d.tut03.CpuPositionOffset;
import com.mundoludo.modern3d.tut03.VertPositionOffset;
import com.mundoludo.modern3d.tut03.VertCalcOffset;
import com.mundoludo.modern3d.tut03.FragChangeColor;
import com.mundoludo.modern3d.tut04.OrthoCube;
import com.mundoludo.modern3d.tut04.ShaderPerspective;
import com.mundoludo.modern3d.tut04.MatrixPerspective;
import com.mundoludo.modern3d.tut04.AspectRatio;

public class App {

    public static void main(String[] args) {
        System.out.println();
        System.out.println("Current available tasks:");
        System.out.println("------------------------");
        System.out.println("\nTutorial 01");
        System.out.println("-----------");
        System.out.println("gradlew hello_triangle");
        System.out.println("\nTutorial 02");
        System.out.println("-----------");
        System.out.println("gradlew fragment_position");
        System.out.println("gradlew vertex_colors");
        System.out.println("\nTutorial 03");
        System.out.println("-----------");
        System.out.println("gradlew cpu_position_offset");
        System.out.println("gradlew shader_position_offset");
        System.out.println("gradlew shader_calc_offset");
        System.out.println("gradlew frag_change_color");
        System.out.println("\nTutorial 04");
        System.out.println("-----------");
        System.out.println("gradlew ortho_cube");
        System.out.println("gradlew shader_perspective");
        System.out.println("gradlew matrix_perspective");
        System.out.println("gradlew aspect_ratio");
        System.out.println("\nTutorial 05");
        System.out.println("-----------");
        System.out.println("gradlew overlap_no_depth");
        System.out.println("gradlew base_vertex_overlap");
        System.out.println("gradlew depth_buffer");
    }
}
